# Generated by Django 6.0.4 on 2026-04-27 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('racao', 'Ração'), ('medicamentos', 'Medicamentos'), ('limpeza', 'Produtos de limpeza'), ('outros', 'Outros')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('consulta', 'Consulta'), ('castracao', 'Castração'), ('exame', 'Exame'), ('procedimento', 'Procedimento'), ('adocao', 'Taxa de adoção'), ('microchip', 'Microchip'), ('prefeitura', 'Verba da prefeitura'), ('outros', 'Outros')], max_length=20)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_ong', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('valor_veterinaria', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('data', models.DateField()),
            ],
        ),
    ]
